# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14efc60ef5d35a21b0bf3107a152b6d89e940aec8c63d89a74fc18d09f8434777eb1ada43fb4db18bae50d69eede18dd367894591f339a93a36e8cfc2757ce8f

test:
  secret_key_base: e820843c658f652182115843751ae387eb3d52aa6e61da13bd80957ce74f59cb5c6a939dede6f23172de9610bc3603264f5940523db25c2942e45de7ce7f4248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
